In [118]:
import pandas as pd
import psycopg2
from collections import Counter

In [119]:
df = pd.read_csv("C:/Users/sowmk/Documents/python/case/data.csv")
df.columns = ['title','genre','tags','languages','Movie_Series','hidden_gem_score','country_available','runtime',
'director','writer','actors','view_rating','imdb_score','rotten_tomatoes_score','metacritic_score','awards_received',
'awards_nominated_for','box_office','release_date','netflix_relase_date','production_house','netflix_link','imdb_link',
'summary','imdb_votes','image','poster','tmdb_trailer','trailer_site']
df.head(5)

,title,genre,tags,languages,Movie_Series,hidden_gem_score,country_available,runtime,director,writer,...,netflix_relase_date,production_house,netflix_link,imdb_link,summary,imdb_votes,image,poster,tmdb_trailer,trailer_site
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Comedy Programmes,Romantic TV Comedies,Horror ...","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,...,2021-03-04,"Canal+, Sandrew Metronome",https://www.netflix.com/watch/81415947,https://www.imdb.com/title/tt1139797,A med student with a supernatural gift tries t...,205926.0,https://occ-0-4708-64.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BOWM4NT...,NaN,NaN
1,HOW TO BUILD A GIRL,Comedy,"Dramas,Comedies,Films Based on Books,British",English,Movie,7.0,Canada,1-2 hour,Coky Giedroyc,Caitlin Moran,...,2021-03-04,"Film 4, Monumental Pictures, Lionsgate",https://www.netflix.com/watch/81041267,https://www.imdb.com/title/tt4193072,"When nerdy Johanna moves to London, things get...",2838.0,https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BZGUyN2...,https://www.youtube.com/watch?v=eIbcxPy4okQ,YouTube
2,Centigrade,"Drama, Thriller",Thrillers,English,Movie,6.4,Canada,1-2 hour,Brendan Walsh,"Brendan Walsh, Daley Nixon",...,2021-03-04,NaN,https://www.netflix.com/watch/81305978,https://www.imdb.com/title/tt8945942,"Trapped in a frozen car during a blizzard, a p...",1720.0,https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BODM2MD...,https://www.youtube.com/watch?v=0RvV7TNUlkQ,YouTube
3,ANNE+,Drama,"TV Dramas,Romantic TV Dramas,Dutch TV Shows",Turkish,Series,7.7,"Belgium,Netherlands",< 30 minutes,NaN,NaN,...,2021-03-04,NaN,https://www.netflix.com/watch/81336456,https://www.imdb.com/title/tt6132758,"Upon moving into a new place, a 20-something r...",1147.0,https://occ-0-1489-1490.1.nflxso.net/dnm/api/v...,https://m.media-amazon.com/images/M/MV5BNWRkMz...,NaN,NaN
4,Moxie,"Animation, Short, Drama","Social Issue Dramas,Teen Movies,Dramas,Comedie...",English,Movie,8.1,"Lithuania,Poland,France,Iceland,Italy,Spain,Gr...",1-2 hour,Stephen Irwin,NaN,...,2021-03-04,NaN,https://www.netflix.com/watch/81078393,https://www.imdb.com/title/tt2023611,Inspired by her moms rebellious past and a con...,63.0,https://occ-0-4039-1500.1.nflxso.net/dnm/api/v...,https://m.media-amazon.com/images/M/MV5BODYyNW...,NaN,NaN

In [120]:
#df.groupby('Movie_Series').count()
df['Movie_Series'].value_counts()

Movie     11697
Series     3783
Name: Movie_Series, dtype: int64

In [121]:
#df[df['title'].str.lower().duplicated()].sort_values(by='title')
movies = df[df['Movie_Series'] == "Movie"].reset_index(level = 0)
movie_id = movies.index +1
movies.insert(0,"movie_id",movie_id)

movies_df = movies[['movie_id','title', 'Movie_Series','runtime','view_rating','imdb_score','rotten_tomatoes_score','metacritic_score','box_office','awards_received','release_date','netflix_relase_date']]
movies_df.head()

,movie_id,title,Movie_Series,runtime,view_rating,imdb_score,rotten_tomatoes_score,metacritic_score,box_office,awards_received,release_date,netflix_relase_date
0,1,HOW TO BUILD A GIRL,Movie,1-2 hour,R,5.8,79.0,69.0,"$70,632",1.0,08 May 2020,2021-03-04
1,2,Centigrade,Movie,1-2 hour,Unrated,4.3,NaN,46.0,"$16,263",NaN,28 Aug 2020,2021-03-04
2,3,Moxie,Movie,1-2 hour,NaN,6.3,NaN,NaN,NaN,NaN,22 Sep 2011,2021-03-04
3,4,The Con-Heartist,Movie,> 2 hrs,NaN,7.4,NaN,NaN,NaN,NaN,03 Dec 2020,2021-03-03
4,5,Only a Mother,Movie,1-2 hour,NaN,6.7,NaN,NaN,NaN,2.0,31 Oct 1949,2021-03-03

In [122]:
movies_df.runtime.drop_duplicates()

runtime_conversion = {"1-2 hour":120,"> 2 hrs":180,"< 30 minutes":30,"30-60 mins":60}
movies_df = movies_df.replace({"runtime":runtime_conversion})
movies_df.head()

,movie_id,title,Movie_Series,runtime,view_rating,imdb_score,rotten_tomatoes_score,metacritic_score,box_office,awards_received,release_date,netflix_relase_date
0,1,HOW TO BUILD A GIRL,Movie,120,R,5.8,79.0,69.0,"$70,632",1.0,08 May 2020,2021-03-04
1,2,Centigrade,Movie,120,Unrated,4.3,NaN,46.0,"$16,263",NaN,28 Aug 2020,2021-03-04
2,3,Moxie,Movie,120,NaN,6.3,NaN,NaN,NaN,NaN,22 Sep 2011,2021-03-04
3,4,The Con-Heartist,Movie,180,NaN,7.4,NaN,NaN,NaN,NaN,03 Dec 2020,2021-03-03
4,5,Only a Mother,Movie,120,NaN,6.7,NaN,NaN,NaN,2.0,31 Oct 1949,2021-03-03

In [123]:
#movies_df['view_rating'].fillna("NA",inplace=True)
movies_df = movies_df.fillna({'view_rating':'NA','production_house':'NA'})
movies_df = movies_df.fillna({'imdb_score':0,'rotten_tomatoes_score':0, 'metacritic_score':0 ,
                               'awards_received':0,'box_office':0})
#movies_df = movies_df.fillna({"release_date":"12 Dec 9999"})
movies_df.head()

,movie_id,title,Movie_Series,runtime,view_rating,imdb_score,rotten_tomatoes_score,metacritic_score,box_office,awards_received,release_date,netflix_relase_date
0,1,HOW TO BUILD A GIRL,Movie,120,R,5.8,79.0,69.0,"$70,632",1.0,08 May 2020,2021-03-04
1,2,Centigrade,Movie,120,Unrated,4.3,0.0,46.0,"$16,263",0.0,28 Aug 2020,2021-03-04
2,3,Moxie,Movie,120,NA,6.3,0.0,0.0,0,0.0,22 Sep 2011,2021-03-04
3,4,The Con-Heartist,Movie,180,NA,7.4,0.0,0.0,0,0.0,03 Dec 2020,2021-03-03
4,5,Only a Mother,Movie,120,NA,6.7,0.0,0.0,0,2.0,31 Oct 1949,2021-03-03

In [124]:
rating = {'R' : 'Restricted','Unrated' : 'NA','NA':'NA','PG-13':'Cautious','PG':'Everyone','TV-Y7':'Everyone','Not Rated':'NA',
'TV-14' : 'Cautious','Approved' : 'Everyone','TV-MA' : 'Restricted','G':'Everyone','Passed':'Everyone',
'TV-Y': 'Everyone','TV-PG' : 'Restricted', 'GP': 'Cautious','TV-G' : 'Everyone','MA-17' : 'Cautious','UNRATED' : 'NA',
'M/PG': 'Cautious','TV-Y7-FV': 'Everyone','X': 'Restricted','NC-17':'Restricted','NOT RATED': 'NA',
'E': 'Cautious','E10+': 'Everyone'}
movies_df = movies_df.replace({"view_rating":rating})
movies_df.head()

,movie_id,title,Movie_Series,runtime,view_rating,imdb_score,rotten_tomatoes_score,metacritic_score,box_office,awards_received,release_date,netflix_relase_date
0,1,HOW TO BUILD A GIRL,Movie,120,Restricted,5.8,79.0,69.0,"$70,632",1.0,08 May 2020,2021-03-04
1,2,Centigrade,Movie,120,NA,4.3,0.0,46.0,"$16,263",0.0,28 Aug 2020,2021-03-04
2,3,Moxie,Movie,120,NA,6.3,0.0,0.0,0,0.0,22 Sep 2011,2021-03-04
3,4,The Con-Heartist,Movie,180,NA,7.4,0.0,0.0,0,0.0,03 Dec 2020,2021-03-03
4,5,Only a Mother,Movie,120,NA,6.7,0.0,0.0,0,2.0,31 Oct 1949,2021-03-03

In [125]:
#movies_df['box_office'] = movies_df['box_office'].str.replace("$","")
#movies_df['box_office'] = movies_df['box_office'].str.replace(",","")
#movies_df['box_office'] = movies_df['box_office'].fillna('0')

movies_df['box_office'] = movies_df['box_office'].str.strip("$")
movies_df['box_office'] = movies_df['box_office'].str.replace(",","")
movies_df['box_office'] = movies_df['box_office'].fillna('0')
movies_df['box_office'].astype('int64')
movies_df.head()

,movie_id,title,Movie_Series,runtime,view_rating,imdb_score,rotten_tomatoes_score,metacritic_score,box_office,awards_received,release_date,netflix_relase_date
0,1,HOW TO BUILD A GIRL,Movie,120,Restricted,5.8,79.0,69.0,70632,1.0,08 May 2020,2021-03-04
1,2,Centigrade,Movie,120,NA,4.3,0.0,46.0,16263,0.0,28 Aug 2020,2021-03-04
2,3,Moxie,Movie,120,NA,6.3,0.0,0.0,0,0.0,22 Sep 2011,2021-03-04
3,4,The Con-Heartist,Movie,180,NA,7.4,0.0,0.0,0,0.0,03 Dec 2020,2021-03-03
4,5,Only a Mother,Movie,120,NA,6.7,0.0,0.0,0,2.0,31 Oct 1949,2021-03-03

In [126]:
movies_df['release_date']  = pd.to_datetime(movies_df['release_date'])
movies_df['release_date']  = movies_df['release_date'].fillna(pd.to_datetime("2099-12-31"))

release_yr = movies_df['release_date'].dt.year
release_qtr = movies_df['release_date'].dt.quarter
movies_df.insert(11,"release_year",release_yr)
movies_df.insert(12,"release_qtr",release_qtr)
movies_df.head()

,movie_id,title,Movie_Series,runtime,view_rating,imdb_score,rotten_tomatoes_score,metacritic_score,box_office,awards_received,release_date,release_year,release_qtr,netflix_relase_date
0,1,HOW TO BUILD A GIRL,Movie,120,Restricted,5.8,79.0,69.0,70632,1.0,2020-05-08,2020,2,2021-03-04
1,2,Centigrade,Movie,120,NA,4.3,0.0,46.0,16263,0.0,2020-08-28,2020,3,2021-03-04
2,3,Moxie,Movie,120,NA,6.3,0.0,0.0,0,0.0,2011-09-22,2011,3,2021-03-04
3,4,The Con-Heartist,Movie,180,NA,7.4,0.0,0.0,0,0.0,2020-12-03,2020,4,2021-03-03
4,5,Only a Mother,Movie,120,NA,6.7,0.0,0.0,0,2.0,1949-10-31,1949,4,2021-03-03

In [127]:
movies_df['netflix_relase_date'] = pd.to_datetime(movies_df['netflix_relase_date'])

nt_release_yr = movies_df['netflix_relase_date'].dt.year
nt_release_qtr = movies_df['netflix_relase_date'].dt.quarter

movies_df.insert(14,"netflix_release_yr",nt_release_yr)
movies_df.insert(15,"netflix_release_qtr",nt_release_qtr)

movies_df.head()

,movie_id,title,Movie_Series,runtime,view_rating,imdb_score,rotten_tomatoes_score,metacritic_score,box_office,awards_received,release_date,release_year,release_qtr,netflix_relase_date,netflix_release_yr,netflix_release_qtr
0,1,HOW TO BUILD A GIRL,Movie,120,Restricted,5.8,79.0,69.0,70632,1.0,2020-05-08,2020,2,2021-03-04,2021,1
1,2,Centigrade,Movie,120,NA,4.3,0.0,46.0,16263,0.0,2020-08-28,2020,3,2021-03-04,2021,1
2,3,Moxie,Movie,120,NA,6.3,0.0,0.0,0,0.0,2011-09-22,2011,3,2021-03-04,2021,1
3,4,The Con-Heartist,Movie,180,NA,7.4,0.0,0.0,0,0.0,2020-12-03,2020,4,2021-03-03,2021,1
4,5,Only a Mother,Movie,120,NA,6.7,0.0,0.0,0,2.0,1949-10-31,1949,4,2021-03-03,2021,1

In [149]:
#g = df['genre'].str.split(",",expand = True).stack().reset_index(drop=True, level = 1).rename('genre')
#genre_df = df[['id','title']].join(g)
#genre_df.head(10)

genre_list = movies['genre'].str.split(",",expand =True).stack().reset_index(drop=True, level =1).rename('genre')
#len(set(genre_list.str.lower().to_list()))
genre_list = genre_list.str.strip().to_list()
genre_list = [x.lower() for x in genre_list]
genre_count = dict(Counter(genre_list))
genre_count_sort = sorted(genre_count.items(), key= lambda x:x[1], reverse=True)
genre_top = { k:v for k,v in dict(genre_count_sort).items() }
genre_top_list =pd.DataFrame(list(genre_top.keys()))
genre_top_list = genre_top_list.replace("-","")

In [150]:
movies = movies.fillna({'genre':'NA', 'tags':'NA','languages':'NA' ,'production_house':'NA'})
#movies.info()

In [151]:
movie_genre = movies['genre'].str.split(",",expand =True).stack().reset_index(drop=True, level =1).rename('genre')
movies_genre_df = movies[['movie_id','title']].join(movie_genre)
movies_genre_df.head(10)

   movie_id                title      genre
0         1  HOW TO BUILD A GIRL     Comedy
1         2           Centigrade      Drama
1         2           Centigrade   Thriller
2         3                Moxie  Animation
2         3                Moxie      Short
2         3                Moxie      Drama
3         4     The Con-Heartist     Comedy
3         4     The Con-Heartist    Romance
4         5        Only a Mother      Drama
5         6           Snowroller     Comedy

In [152]:
g = pd.DataFrame({"id" : [1,2,3], "genre" : ['drama','comedy','comedy,drama']})

glist = g['genre'].to_dict()
glist

val ={}

for k,v in glist.items():
    if 'drama' in v:
        val[k]='Y'
    else:
        val[k] = 'N'
val

flag = pd.DataFrame(val, index=[0])
flag =flag.T

g.join(flag)

   id         genre  0
0   1         drama  Y
1   2        comedy  N
2   3  comedy,drama  Y

In [153]:
gdf = movies[['movie_id','title','genre']]

gdf_list = gdf['genre'].to_dict()
gdf_list

{0: 'Comedy',
 1: 'Drama, Thriller',
 2: 'Animation, Short, Drama',
 3: 'Comedy, Romance',
 4: 'Drama',
 5: 'Comedy',
 6: 'Comedy, Family, Fantasy',
 7: 'Crime, Drama, Fantasy, Mystery, Thriller',
 8: 'Drama',
 9: 'Comedy, Drama',
 10: 'Short, Drama',
 11: 'Crime, Drama, Thriller',
 12: 'Action, Adventure, Fantasy, Sci-Fi',
 13: 'Adventure, Drama, Fantasy, Mystery',
 14: 'Music',
 15: 'Drama, Thriller',
 16: 'Short',
 17: 'Thriller',
 18: 'Drama',
 19: 'Comedy, Drama',
 20: 'Drama, Romance',
 21: 'Comedy',
 22: 'Action, Family, Sci-Fi, Thriller',
 23: 'Biography, Drama, Thriller',
 24: 'Drama',
 25: 'Crime, Drama',
 26: 'Drama',
 27: 'Drama',
 28: 'Action, Family, Sci-Fi, Thriller',
 29: 'Drama',
 30: 'Drama, Romance',
 31: 'Animation, Drama, Sport',
 32: 'NA',
 33: 'Drama, Romance',
 34: 'Biography, Drama',
 35: 'Comedy',
 36: 'Animation, Adventure, Family, Mystery',
 37: 'Comedy',
 38: 'Drama, War',
 39: 'Drama, History, War',
 40: 'Comedy, Crime, Drama',
 41: 'Adventure, Drama, Sci-Fi, Thriller',
 42: 'Documentary, Biography, Drama',
 43: 'Comedy, Horror, Sci-Fi',
 44: 'Comedy, Crime',
 45: 'Crime',
 46: 'Mystery, Thriller',
 47: 'Drama',
 48: 'Documentary',
 49: 'Drama',
 50: 'Comedy, Fantasy, Horror, Thriller',
 51: 'Drama',
 52: 'Biography, Drama, Romance, War',
 53: 'Biography, Drama, Romance, War',
 54: 'Drama',
 55: 'Crime, Drama',
 56: 'Drama, Crime, Action',
 57: 'Action, Crime, Fantasy, Thriller',
 58: 'Adventure, Drama',
 59: 'Animation, Adventure',
 60: 'Drama, Romance',
 61: 'Animation',
 62: 'Adventure, Drama, Mystery',
 63: 'Comedy, Drama, Family',
 64: 'Drama, Romance, Thriller',
 65: 'Comedy, History, Romance',
 66: 'Comedy, Drama',
 67: 'Horror',
 68: 'Action, Drama, Thriller',
 69: 'Action, Comedy, Crime',
 70: 'Drama',
 71: 'Action, Crime, Drama, Horror, Thriller',
 72: 'Short, Drama',
 73: 'Comedy, Crime, Thriller',
 74: 'Thriller',
 75: 'Crime, Drama, Film-Noir, Thriller',
 76: 'Action, Drama, Fantasy, Thriller',
 77: 'Drama',
 78: 'Action',
 79: 'Comedy, Crime, Thriller',
 80: 'Horror, Thriller',
 81: 'Drama',
 82: 'Action, Comedy',
 83: 'Animation, Family',
 84: 'Crime, Drama, Mystery, Thriller',
 85: 'Animation, Short',
 86: 'Animation, Comedy, Drama, Family, Fantasy, Romance',
 87: 'Comedy, Drama',
 88: 'Comedy, Drama, Romance',
 89: 'Drama, Music, Thriller',
 90: 'Animation',
 91: 'Biography, Crime, Drama',
 92: 'Thriller',
 93: 'Action, Biography, Crime, Thriller',
 94: 'Biography, Crime, Drama, Thriller, War',
 95: 'Action, Comedy, Crime, Thriller',
 96: 'Documentary',
 97: 'Horror, Mystery, Thriller',
 98: 'Comedy, Drama',
 99: 'Documentary',
 100: 'Comedy',
 101: 'Comedy, Crime, Thriller',
 102: 'Horror, Mystery, Thriller',
 103: 'Action, Thriller',
 104: 'Sci-Fi',
 105: 'Comedy, Musical',
 106: 'Drama',
 107: 'Documentary',
 108: 'Drama, Romance',
 109: 'Comedy, Drama',
 110: 'Crime, Horror, Thriller',
 111: 'Action',
 112: 'Drama',
 113: 'Comedy, Drama, Fantasy, Romance',
 114: 'Drama, History, Romance, War',
 115: 'Action',
 116: 'Drama',
 117: 'Drama',
 118: 'Action, Adventure, Crime, Fantasy, Mystery, Thriller',
 119: 'Documentary, Sport',
 120: 'Drama',
 121: 'Drama, Thriller',
 122: 'Action, Comedy, Crime, Drama, Thriller',
 123: 'Action, Thriller',
 124: 'Documentary',
 125: 'Action, Comedy, Crime, Sci-Fi, Thriller',
 126: 'Drama, Romance, Sport',
 127: 'Comedy, Drama',
 128: 'Drama, Mystery, Thriller',
 129: 'Action, Comedy, Sport',
 130: 'Action, Crime, Thriller',
 131: 'Adventure, Comedy, Drama',
 132: 'Drama, Romance',
 133: 'Drama',
 134: 'Comedy, Crime, Thriller',
 135: 'Drama, Romance',
 136: 'Comedy, Drama',
 137: 'Comedy',
 138: 'Drama, Romance',
 139: 'Comedy, Drama, History',
 140: 'Drama, Romance',
 141: 'Documentary',
 142: 'Comedy, Drama, Romance',
 143: 'Drama, Romance',
 144: 'Drama, Romance',
 145: 'Animation, Drama, Fantasy, Romance',
 146: 'Comedy, Sci-Fi, Thriller',
 147: 'Adventure, Comedy, Fantasy, Sci-Fi',
 148: 'Drama, Mystery, Thriller',
 149: 'Comedy, Crime',
 150: 'Adventure, Drama, Family',
 151: 'Comedy, Romance',
 152: 'Action, Adventure, Drama, Western',
 153: 'Drama, Family',
 154: 'Comedy, Drama, Music, Romance',
 155: 'Action, Comedy, Sci-Fi',
 156: 'Drama',
 157: 'Documentary',
 158: 'Action, Comedy, Crime, Thriller',
 159: 'Comedy, Drama',
 160: 'Drama, Comedy',
 161: 'Drama',
 162: 'Comedy',
 163: 'Action, Adventure, Drama, Fantasy, Sci-Fi',
 164: 'Documentary',
 165: 'Comedy, Crime, Sci-Fi',
 166: 'Drama',
 167: 'NA',
 168: 'Biography, Drama, Music, Romance',
 169: 'Drama',
 170: 'Action, Drama, Fantasy, Mystery, Sci-Fi',
 171: 'Comedy',
 172: 'Drama, History, Romance',
 173: 'Crime, Mystery, Thriller',
 174: 'Comedy, Drama, Family',
 175: 'Adventure, Drama, Family',
 176: 'Action, History, Thriller',
 177: 'Comedy, Drama, Fantasy',
 178: 'Drama, Family',
 179: 'Drama',
 180: 'Drama',
 181: 'Comedy, Drama',
 182: 'Drama',
 183: 'Drama',
 184: 'Comedy',
 185: 'Comedy, Romance',
 186: 'Drama',
 187: 'Action, Comedy, Crime, Drama, Thriller',
 188: 'Comedy',
 189: 'Short, Comedy',
 190: 'Action, Drama, Fantasy, Thriller',
 191: 'Drama, War',
 192: 'Action, Adventure, Drama, Fantasy, Thriller',
 193: 'Documentary, Music',
 194: 'Horror',
 195: 'Animation, Action, Adventure, Fantasy',
 196: 'Action, Drama, Thriller, War',
 197: 'Crime, Drama',
 198: 'Documentary',
 199: 'Comedy, Drama',
 200: 'Comedy, Drama',
 201: 'Drama, Comedy',
 202: 'Action, Crime, Drama',
 203: 'Comedy, Romance',
 204: 'Action, Adventure, Comedy, Family, Romance, Sport, Western',
 205: 'Animation, Action, Sci-Fi',
 206: 'Comedy',
 207: 'Biography, Comedy, Drama',
 208: 'Action, Adventure, Fantasy, Sci-Fi',
 209: 'Drama, War',
 210: 'Documentary',
 211: 'Musical',
 212: 'Drama',
 213: 'Crime, Drama, Horror, Thriller',
 214: 'Animation, Adventure, Comedy, Family, Fantasy, Musical',
 215: 'Thriller',
 216: 'Short, Comedy',
 217: 'Short, Comedy',
 218: 'Drama, Romance',
 219: 'Fantasy, Horror',
 220: 'Comedy',
 221: 'Action, Adventure, Comedy, Sci-Fi',
 222: 'Drama, Horror, Mystery, Thriller',
 223: 'Crime, Drama',
 224: 'Drama',
 225: 'Drama',
 226: 'NA',
 227: 'Comedy, Drama',
 228: 'Drama',
 229: 'Comedy, Drama',
 230: 'Adventure, Comedy, Drama',
 231: 'Crime',
 232: 'Animation',
 233: 'Film-Noir, Mystery, Thriller',
 234: 'Comedy, Drama',
 235: 'Action, Comedy, Fantasy, Sci-Fi, Thriller',
 236: 'Drama, War',
 237: 'Comedy, Drama, Thriller',
 238: 'Comedy, Drama',
 239: 'Animation, Adventure, Comedy, Family, Fantasy',
 240: 'Comedy, Drama',
 241: 'Drama',
 242: 'Documentary, Drama',
 243: 'Drama',
 244: 'Drama, Romance',
 245: 'Comedy',
 246: 'Comedy',
 247: 'Comedy',
 248: 'Documentary',
 249: 'Drama, History',
 250: 'Documentary, Music',
 251: 'Drama',
 252: 'Crime, Drama',
 253: 'Short, Action',
 254: 'Biography, Drama, Music, Romance',
 255: 'Crime, Drama',
 256: 'Action, Crime, Drama, Thriller',
 257: 'Comedy, Drama, Romance',
 258: 'Action, Crime, Drama, Thriller',
 259: 'Adventure, Drama, Fantasy',
 260: 'Drama, Mystery, Thriller',
 261: 'Adventure, Drama, Thriller',
 262: 'Adventure, Drama, Horror',
 263: 'Comedy',
 264: 'Short, Fantasy, Horror',
 265: 'Drama, Thriller',
 266: 'Drama, History',
 267: 'Horror, Mystery, Thriller',
 268: 'Drama',
 269: 'Comedy, Romance, Sport',
 270: 'Short, Comedy, Horror',
 271: 'Drama',
 272: 'Action, Mystery, Thriller',
 273: 'Action, Thriller',
 274: 'Documentary, Short, Biography',
 275: 'Action, Adventure, Fantasy, Sci-Fi',
 276: 'Comedy, Drama, Family',
 277: 'Adventure, Drama',
 278: 'Animation, Comedy, Drama, Romance',
 279: 'Action, Drama, Romance, Thriller',
 280: 'Drama',
 281: 'Crime, Thriller',
 282: 'Animation',
 283: 'Drama, Mystery',
 284: 'Drama',
 285: 'Animation, Adventure, Drama, Family, Fantasy',
 286: 'Drama',
 287: 'Drama, Thriller, Western',
 288: 'Adventure, Drama, Sci-Fi',
 289: 'Comedy',
 290: 'Drama, Horror, Sci-Fi, Thriller',
 291: 'Action, Crime, Drama',
 292: 'Action, Drama, Family',
 293: 'Crime',
 294: 'Crime, Drama',
 295: 'Comedy, Crime',
 296: 'Documentary, Crime, History',
 297: 'Drama, Romance',
 298: 'NA',
 299: 'Action, Crime, Drama, Thriller',
 300: 'Comedy',
 301: 'Comedy, Short',
 302: 'Drama, Romance',
 303: 'Documentary, Sport',
 304: 'Biography, Crime, Drama',
 305: 'Drama',
 306: 'Biography, Drama, History',
 307: 'Documentary, Short',
 308: 'Comedy, Drama',
 309: 'Drama',
 310: 'Documentary, Biography, Sport',
 311: 'Drama',
 312: 'Action, Drama, Horror, Thriller',
 313: 'Drama',
 314: 'Comedy, Crime, Drama',
 315: 'Comedy',
 316: 'Comedy, Drama',
 317: 'Family',
 318: 'Adventure, Comedy',
 319: 'Comedy, Horror, Thriller',
 320: 'Documentary',
 321: 'Drama, Family, Music, Romance',
 322: 'Action, Comedy, Fantasy, Romance',
 323: 'Crime, Drama, Thriller',
 324: 'Drama',
 325: 'Documentary, Action, Crime, Drama',
 326: 'Comedy, Drama',
 327: 'Documentary',
 328: 'Crime, Drama, Thriller',
 329: 'Romance',
 330: 'Animation, Comedy, Drama, Horror, Mystery, Thriller',
 331: 'Thriller',
 332: 'Drama',
 333: 'Comedy, Drama, Family',
 334: 'Drama, Romance, Sport',
 335: 'Animation, Adventure, Comedy, Family, Fantasy, Mystery, Sci-Fi',
 336: 'Animation, Adventure, Musical',
 337: 'Comedy, Romance',
 338: 'Biography',
 339: 'Action, Horror, Sci-Fi, Thriller',
 340: 'Biography, Drama',
 341: 'Drama, Romance',
 342: 'Drama, Romance',
 343: 'Comedy',
 344: 'Drama, Music',
 345: 'Comedy',
 346: 'Short',
 347: 'Short',
 348: 'Action, Comedy, Crime, Music, Musical',
 349: 'Action, Adventure, Drama, Sport, Thriller',
 350: 'Family',
 351: 'Animation, Adventure, Romance',
 352: 'Comedy',
 353: 'Comedy, Drama',
 354: 'Animation, Action, Adventure, Comedy, Drama, Family, Fantasy, Sci-Fi',
 355: 'Animation, Adventure, Comedy, Family, Fantasy',
 356: 'Comedy, Crime, Thriller',
 357: 'Horror, Mystery, Thriller',
 358: 'Crime, Drama, Thriller',
 359: 'Comedy, Drama',
 360: 'Action, Drama',
 361: 'Action, Adventure, Drama, Sci-Fi',
 362: 'Drama, Romance',
 363: 'Short, Horror, Sci-Fi, Thriller',
 364: 'Short, Comedy, Drama, Fantasy',
 365: 'Action, Crime, Drama',
 366: 'Comedy, Drama, Thriller',
 367: 'Comedy, Crime, Drama, Romance, Thriller',
 368: 'Action, Crime, Drama',
 369: 'Drama',
 370: 'Drama, Fantasy, Mystery',
 371: 'Adventure, Drama',
 372: 'Comedy, Drama, Sport',
 373: 'Drama',
 374: 'Crime, Drama, Mystery, Thriller',
 375: 'Comedy',
 376: 'Comedy',
 377: 'Comedy, Sport',
 378: 'Comedy',
 379: 'Horror',
 380: 'Drama, Romance',
 381: 'Drama, Romance',
 382: 'Short, Drama, Mystery, Sci-Fi',
 383: 'Comedy, Drama',
 384: 'Action, Crime, Romance',
 385: 'Crime, Horror, Mystery, Sci-Fi',
 386: 'Comedy, Drama',
 387: 'Action',
 388: 'Comedy',
 389: 'Biography, Crime, Drama, Mystery, Thriller',
 390: 'Animation, Crime, Horror, Mystery, Thriller',
 391: 'Action, Crime, Thriller',
 392: 'Action, Crime',
 393: 'Adventure, Drama, Sci-Fi, Thriller',
 394: 'Crime, Drama, Thriller',
 395: 'Drama',
 396: 'Horror',
 397: 'Comedy, Drama, Family',
 398: 'Adventure, Drama, Horror, Mystery, Sci-Fi, Thriller',
 399: 'Comedy, Family',
 400: 'NA',
 401: 'Comedy',
 402: 'Drama',
 403: 'Drama',
 404: 'Comedy',
 405: 'Short, Action, Adventure, Fantasy',
 406: 'Action, Fantasy, Sci-Fi',
 407: 'Drama, War',
 408: 'Animation, Action, Sci-Fi',
 409: 'Biography, Crime, Drama',
 410: 'Drama, Family',
 411: 'Drama, Romance',
 412: 'Thriller',
 413: 'Action, Crime, Drama, Thriller',
 414: 'Comedy',
 415: 'Drama, Romance',
 416: 'Drama',
 417: 'Reality-TV',
 418: 'Biography, Drama, Romance',
 419: 'Thriller',
 420: 'Drama, Mystery, Thriller',
 421: 'Action, Adventure, Horror, Sci-Fi, Thriller',
 422: 'Drama, Fantasy, Mystery, Thriller',
 423: 'Animation, Adventure, Comedy, Family',
 424: 'Animation, Action, Comedy, Sci-Fi',
 425: 'Animation, Action, Comedy, Sci-Fi',
 426: 'Action, Comedy',
 427: 'Action, Adventure, Drama, Horror, Thriller',
 428: 'Comedy',
 429: 'Comedy, Drama',
 430: 'Action, Drama, Romance',
 431: 'Documentary',
 432: 'Comedy, Romance',
 433: 'Comedy, Crime, Drama, Thriller',
 434: 'Documentary, Animation, Biography, Comedy',
 435: 'Comedy',
 436: 'Comedy, Romance',
 437: 'Comedy',
 438: 'Animation, Action, Adventure, Comedy, Sci-Fi',
 439: 'Drama, Fantasy, Sci-Fi, Thriller',
 440: 'Drama, Romance',
 441: 'Drama, Romance',
 442: 'Drama, Family',
 443: 'Comedy, Drama',
 444: 'Animation, Short',
 445: 'Comedy, Crime',
 446: 'Drama',
 447: 'Drama',
 448: 'Game-Show, Reality-TV',
 449: 'Action, Adventure, Drama, War',
 450: 'Comedy, Horror, Mystery, Sci-Fi',
 451: 'Family, Fantasy, Music',
 452: 'Comedy, Drama, Music, Romance',
 453: 'Animation, Adventure, Comedy, Family, Fantasy',
 454: 'Documentary, Music',
 455: 'Action, Comedy, Crime',
 456: 'NA',
 457: 'Comedy',
 458: 'Drama, Horror, Mystery, Sci-Fi, Thriller',
 459: 'Documentary',
 460: 'Comedy, Drama, Family',
 461: 'Drama',
 462: 'Drama',
 463: 'Drama, Music, Romance',
 464: 'Comedy, Drama',
 465: 'Comedy',
 466: 'Adventure, Comedy, Drama, Romance',
 467: 'Comedy, Romance',
 468: 'Drama, Fantasy, Romance, Sci-Fi',
 469: 'Comedy',
 470: 'Action, Sci-Fi, Thriller',
 471: 'Drama',
 472: 'Crime, Drama, Mystery',
 473: 'Comedy',
 474: 'Comedy, Family, Fantasy',
 475: 'Action, Comedy',
 476: 'Drama, Horror, Thriller',
 477: 'Biography, Drama',
 478: 'Documentary, Biography',
 479: 'Documentary',
 480: 'Action, Adventure, Comedy, Crime, Thriller',
 481: 'Comedy, Music',
 482: 'Comedy',
 483: 'Comedy',
 484: 'Comedy, Horror, Mystery, Thriller',
 485: 'Drama',
 486: 'Drama',
 487: 'Biography, Drama',
 488: 'Drama',
 489: 'Animation, Short',
 490: 'Biography, Crime, Drama',
 491: 'Adventure, Comedy',
 492: 'Comedy, Drama, Romance',
 493: 'Action, Drama, Horror',
 494: 'Family',
 495: 'Comedy',
 496: 'Comedy, Romance',
 497: 'Horror',
 498: 'Comedy, Sport',
 499: 'Comedy',
 500: 'Short, Drama, Thriller',
 501: 'Drama, Music, Romance',
 502: 'Thriller',
 503: 'Comedy, Drama',
 504: 'Short, Action, Drama, Sci-Fi, Thriller',
 505: 'Drama, Sci-Fi',
 506: 'Short',
 507: 'Horror',
 508: 'Drama, Horror, Mystery, Thriller',
 509: 'Drama, History, War',
 510: 'Drama',
 511: 'Drama, Romance',
 512: 'Comedy, Romance',
 513: 'Action, Drama, Sport',
 514: 'Crime, Drama, Romance, Thriller',
 515: 'Adventure, Comedy, Fantasy, Western',
 516: 'Comedy',
 517: 'Adventure, Comedy',
 518: 'Comedy, Drama',
 519: 'Drama',
 520: 'Comedy',
 521: 'Drama',
 522: 'Drama, Short',
 523: 'Comedy',
 524: 'Comedy, Crime',
 525: 'Comedy',
 526: 'Drama, Romance',
 527: 'Drama, Thriller',
 528: 'Comedy, Romance',
 529: 'Drama, History',
 530: 'Comedy, Fantasy, Music, Sci-Fi',
 531: 'Action, Crime, Thriller',
 532: 'Adventure, Drama, Romance',
 533: 'Comedy',
 534: 'Crime',
 535: 'Adventure, Family, Fantasy',
 536: 'Comedy, Drama',
 537: 'Drama, Music',
 538: 'Comedy, Crime',
 539: 'Documentary, History',
 540: 'Mystery, Thriller',
 541: 'Comedy, Drama',
 542: 'Documentary, Biography, Comedy',
 543: 'Comedy, Family',
 544: 'Comedy, Drama',
 545: 'Biography, Drama, Family, Music',
 546: 'Drama, Fantasy, Sci-Fi, Thriller',
 547: 'Short, Comedy, Sport',
 548: 'Biography, Crime, Drama',
 549: 'Adventure, Comedy, Drama',
 550: 'Action, Thriller',
 551: 'Horror',
 552: 'Action, Crime',
 553: 'Comedy',
 554: 'Animation, Action, Adventure, Comedy, Mystery, Sci-Fi, Thriller',
 555: 'Action, Crime, Drama, Thriller',
 556: 'Comedy, Musical, Romance',
 557: 'Comedy, Short',
 558: 'Drama, History, Romance, War',
 559: 'Romance',
 560: 'Horror, Mystery, Thriller',
 561: 'Drama, Mystery, Romance',
 562: 'Adventure, Drama, History',
 563: 'Biography, Crime, Drama',
 564: 'Comedy',
 565: 'Animation, Action, Adventure, Comedy, Drama, Fantasy, Sci-Fi, Thriller',
 566: 'Documentary',
 567: 'Action, Drama, Sport, Thriller',
 568: 'Comedy, Drama',
 569: 'Documentary',
 570: 'Comedy, Drama, Music',
 571: 'Animation, Action, Comedy',
 572: 'Drama',
 573: 'Animation, Family',
 574: 'Action',
 575: 'Horror',
 576: 'Drama',
 577: 'Horror, Thriller',
 578: 'Comedy, Drama',
 579: 'Action',
 580: 'Adventure, Fantasy',
 581: 'Comedy',
 582: 'Comedy, Romance',
 583: 'Adventure, Comedy, Drama',
 584: 'Adventure, Comedy, Drama',
 585: 'Comedy, Drama',
 586: 'Drama',
 587: 'Animation, Adventure, Comedy, Drama, Family, Mystery, Western',
 588: 'Drama, Romance',
 589: 'Comedy, Drama',
 590: 'Crime, Drama, Mystery, Thriller',
 591: 'Comedy, Drama, Music',
 592: 'NA',
 593: 'Drama, Romance',
 594: 'Comedy, Fantasy, Romance',
 595: 'Action, Comedy, Sci-Fi, Thriller',
 596: 'Drama, Family, Mystery',
 597: 'Comedy',
 598: 'Comedy, Romance',
 599: 'Horror, Mystery, Thriller',
 600: 'Comedy, Drama, Romance',
 601: 'Short',
 602: 'Drama, Mystery, Sci-Fi, Thriller',
 603: 'Sci-Fi',
 604: 'Horror, Thriller',
 605: 'Comedy, Family, Romance',
 606: 'Documentary, Animation, Short, Drama',
 607: 'Mystery',
 608: 'Comedy, Romance',
 609: 'Animation, Romance',
 610: 'Adventure, Comedy, Drama',
 611: 'Short, Drama',
 612: 'Comedy, Drama, Romance',
 613: 'Animation, Adventure, Comedy, Family, Fantasy',
 614: 'Animation, Family',
 615: 'Drama, Music',
 616: 'Biography, Comedy, Drama',
 617: 'Short, Music',
 618: 'Comedy, Crime, Thriller',
 619: 'Animation, Comedy, Family',
 620: 'Horror, Mystery, Thriller',
 621: 'Biography, Drama',
 622: 'Drama',
 623: 'Comedy, Crime, Drama, Thriller',
 624: 'Comedy, Drama',
 625: 'Animation, Family',
 626: 'Thriller',
 627: 'Sci-Fi, Short',
 628: 'Comedy, Romance',
 629: 'Drama, Romance',
 630: 'Drama, Horror, Mystery, Thriller',
 631: 'Drama',
 632: 'Documentary',
 633: 'Comedy',
 634: 'Documentary',
 635: 'Drama, Romance',
 636: 'Comedy, Drama, Family, Sport',
 637: 'Drama, Romance',
 638: 'Action, Crime, Drama, Thriller',
 639: 'Action, Crime, Drama',
 640: 'Comedy',
 641: 'Drama',
 642: 'Drama, History',
 643: 'Drama, Romance',
 644: 'Drama',
 645: 'Adventure, Comedy, Family, Mystery',
 646: 'Crime, Drama',
 647: 'Drama',
 648: 'Action, Drama, Mystery, Thriller',
 649: 'Sci-Fi, Thriller',
 650: 'Action, Adventure, Family, Fantasy, Sci-Fi',
 651: 'Action, Adventure, Drama, Family, Sci-Fi',
 652: 'Drama',
 653: 'Comedy, Drama',
 654: 'Action, Adventure, Fantasy, Sci-Fi',
 655: 'Action, Adventure, Family, Sci-Fi',
 656: 'Action, Adventure, Fantasy, Sci-Fi, Thriller',
 657: 'Action, Adventure, Drama, Fantasy, Horror, Sci-Fi, Thriller',
 658: 'Action, Horror, Sci-Fi',
 659: 'Action, Sci-Fi',
 660: 'Action, Adventure, Drama, Sci-Fi, Thriller',
 661: 'Action, Adventure, Sci-Fi, Thriller',
 662: 'Action, Horror, Sci-Fi',
 663: 'Action, Adventure, Drama, Sci-Fi',
 664: 'Action, Fantasy, Horror, Sci-Fi',
 665: 'Animation, Action, Adventure, Horror, Music, Sci-Fi',
 666: 'Action, Adventure, Family, Horror, Sci-Fi',
 667: 'Action, Adventure, Sci-Fi, Thriller',
 668: 'Action, Family, Sci-Fi, Thriller',
 669: 'Action, Horror, Sci-Fi',
 670: 'Comedy, Drama',
 671: 'Action, Adventure, Fantasy, Sci-Fi, Thriller',
 672: 'Action, Horror, Sci-Fi, Thriller',
 673: 'Crime, Mystery',
 674: 'Drama, Romance',
 675: 'Drama, Music, Romance',
 676: 'Action, Horror, Sci-Fi',
 677: 'Action, Adventure, Family, Sci-Fi',
 678: 'Action',
 679: 'Action',
 680: 'Drama, War',
 681: 'Crime, Drama',
 682: 'Drama',
 683: 'Animation, Family, Fantasy',
 684: 'Action, Crime, Drama, Thriller',
 685: 'Crime, Drama, Thriller',
 686: 'Action, Drama',
 687: 'Drama',
 688: 'Horror, Mystery, Thriller',
 689: 'Short',
 690: 'Drama',
 691: 'Adventure',
 692: 'Drama, Romance',
 693: 'Drama',
 694: 'Drama',
 695: 'Drama, War',
 696: 'Crime, Drama, Romance',
 697: 'Drama, History',
 698: 'Comedy',
 699: 'Comedy, Drama, War',
 700: 'Action, Comedy',
 701: 'Comedy, Drama, Romance',
 702: 'Family',
 703: 'NA',
 704: 'Comedy, Drama, Thriller',
 705: 'Drama, Sport',
 706: 'Drama',
 707: 'Drama',
 708: 'Drama, Romance',
 709: 'Drama, Romance',
 710: 'Horror',
 711: 'Comedy',
 712: 'Thriller',
 713: 'Drama',
 714: 'Drama, Romance',
 715: 'Comedy',
 716: 'Horror, Thriller',
 717: 'Action, Romance',
 718: 'Comedy, Drama, Musical',
 719: 'Comedy, Musical',
 720: 'NA',

In [154]:
genre_top_list.columns = ['genre']
genre_top_names = genre_top_list['genre'].to_list()
genre_top_names = [x.replace("-","") for x in genre_top_names  ]

genre_top_list1 = genre_top_list['genre'].to_list()
genre_top_list1 = [x+"_flag" for x in genre_top_list1]
genre_top_list1 = [x.replace("-","") for x in genre_top_list1  ]

genre_top_list1
for x in genre_top_list1 : exec(x + "=dict()")

In [155]:
genre_top_dict = { x: 'N' for x in genre_top_names  }
genre_top_dict

{'drama': 'N',
 'comedy': 'N',
 'thriller': 'N',
 'action': 'N',
 'romance': 'N',
 'crime': 'N',
 'adventure': 'N',
 'na': 'N',
 'fantasy': 'N',
 'family': 'N',
 'horror': 'N',
 'scifi': 'N',
 'mystery': 'N',
 'animation': 'N',
 'documentary': 'N',
 'biography': 'N',
 'history': 'N',
 'music': 'N',
 'sport': 'N',
 'war': 'N',
 'short': 'N',
 'musical': 'N',
 'western': 'N',
 'news': 'N',
 'realitytv': 'N',
 'adult': 'N',
 'talkshow': 'N',
 'filmnoir': 'N',
 'gameshow': 'N'}

In [160]:
gflags = {}

for k,v in gdf_list.items():
   #print(v)
   d1 = { x: 'N' for x in genre_top_names  }
   gflags[k] = d1
   for name in v.split(","):
      gflags[k][name.lower().strip().replace("-","")] ='Y'
   
#print(gflags)

gflags_df = pd.DataFrame(gflags)
gflags_df_upd = gflags_df.T
gflags_df_upd

gdf = gdf.join(gflags_df_upd)
gdf.head()

,movie_id,title,genre,drama,comedy,thriller,action,romance,crime,adventure,...,war,short,musical,western,news,realitytv,adult,talkshow,filmnoir,gameshow
0,1,HOW TO BUILD A GIRL,Comedy,N,Y,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,N
1,2,Centigrade,"Drama, Thriller",Y,N,Y,N,N,N,N,...,N,N,N,N,N,N,N,N,N,N
2,3,Moxie,"Animation, Short, Drama",Y,N,N,N,N,N,N,...,N,Y,N,N,N,N,N,N,N,N
3,4,The Con-Heartist,"Comedy, Romance",N,Y,N,N,Y,N,N,...,N,N,N,N,N,N,N,N,N,N
4,5,Only a Mother,Drama,Y,N,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,N